version: '3.8'

services:

  api:
    container_name: nest_api
    build: .
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - .:/home/api
      - /home/api/node_modules

  database:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

