version: '3.8'

services:

  api:
    container_name: nest_api
    build: .
    ports:
      - 3000:3000

  database-postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: jean
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest-graphql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
